#!/bin/bash
#PBS -l select=1:ncpus=1:mem=2gb
#PBS -l walltime=72:00:00
#PBS -N central_builds

module load Julia

cd $PBS_O_WORKDIR

#julia experiments/central_ADMM_builds.jl &
julia experiments/central_builds.jl 
#julia experiments/decentralised_builds.jl &
#julia experiments/decentralised_size.jl &
#julia experiments/opt_builds.jl &
#julia experiments/opt_size.jl &
#julia experiments/private_builds.jl &
#julia experiments/private_size.jl &
